/**
 * Generate `docs/schema.md` from the migration list.
 *
 * Part 14 §14.5 lists `docs/schema.md` as a generated, checked-in artifact, and five doc
 * comments across `@wise-excavate/store` point readers at it. It did not exist, which made those
 * comments false — and left schema v1 reviewable only by reading a TypeScript template
 * literal.
 *
 * Checked in on purpose (Part 14 §14.5): a schema is the thing reviewers most need to read
 * on the web, and a diff of this file is the clearest possible signal that a migration
 * changed the shape of the index.
 *
 * Run: `pnpm gen:schema`. With `--check` it verifies the committed file is current instead
 * of writing, which is what CI should call once M1 adds a second migration.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { argv } from 'node:process';

const OUT = 'docs/schema.md';
const MIGRATIONS_DIR = 'packages/store/src/migrations';

/** Pull the SQL out of a migration module without importing it — this is a plain script. */
function migrationOf(file) {
  const source = readFileSync(`${MIGRATIONS_DIR}/${file}`, 'utf8');
  const version = /version:\s*(\d+)/.exec(source)?.[1];
  const name = /name:\s*'([^']+)'/.exec(source)?.[1];
  const sql = /up:\s*`([\s\S]*?)`,?\s*\n\};/.exec(source)?.[1];
  if (version === undefined || name === undefined || sql === undefined) {
    throw new Error(
      `${file}: could not extract version/name/up. This generator reads the migration ` +
        `modules textually; if their shape changed, update it here rather than hand-editing ${OUT}.`,
    );
  }
  return { version: Number(version), name, sql: sql.trim() };
}

const files = readFileSync(`${MIGRATIONS_DIR}/index.ts`, 'utf8')
  .split('\n')
  .flatMap((line) => /from '\.\/(\d{4}-[a-z0-9-]+)\.js'/.exec(line)?.[1] ?? []);

if (files.length === 0) {
  throw new Error(`no migration modules found via ${MIGRATIONS_DIR}/index.ts`);
}

const migrations = files
  .map((f) => migrationOf(`${f}.ts`))
  .sort((a, b) => a.version - b.version);

const body = `<!-- GENERATED by scripts/gen-schema.mjs from ${MIGRATIONS_DIR}/. Do not edit by hand; run \`pnpm gen:schema\`. -->

# Index schema

The index is a single SQLite file, \`index.db\`, with its FTS5 tables inside it — no
sidecars (LEAN-V1 §5). This page is generated from the migrations, so it cannot drift from
what the code actually creates.

Schema version: **${migrations.at(-1).version}**

Migrations are applied in order and never edited once shipped; a change is always a new
migration. Deliberately absent from v1 and named in \`0001-init.ts\`: the \`hunks\` table and
the derived rollups (M2 artifacts, per LEAN-V1 §3.2) and the evidence-bundle cache.

${migrations
  .map(
    ({ version, name, sql }) =>
      `## ${String(version).padStart(4, '0')} — \`${name}\`\n\n\`\`\`sql\n${sql}\n\`\`\`\n`,
  )
  .join('\n')}`;

if (argv.includes('--check')) {
  const current = (() => {
    try {
      return readFileSync(OUT, 'utf8');
    } catch {
      return null;
    }
  })();
  if (current !== body) {
    console.error(`✗ ${OUT} is stale. Run \`pnpm gen:schema\` and commit the result.`);
    process.exit(1);
  }
  console.log(`✓ ${OUT} is up to date.`);
} else {
  writeFileSync(OUT, body);
  console.log(`✓ wrote ${OUT} (${migrations.length} migration(s))`);
}
